bind r source-file ~/.tmux.conf \; display "Reloaded!" # Reload with ctrl-r
unbind C-b # release C-b for other use(s)
set -g prefix ` # backtick as new prefix
bind-key ` send-prefix # allow backtick to be used for other things
set -sg escape-time 0 # quicker responses
set -g base-index 1 # Numbering of windows
setw -g pane-base-index 1 # Numbering of Panes
set -g default-terminal "screen-256color"
set -g mouse on # allow mouse control
set -g history-limit 10000

# window split remaps (personal taste)
bind-key o split-window -h
bind-key p split-window -v

# vim like pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# window resizing
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

